required = ["github.com/jteeuwen/go-bindata"]

[[constraint]]
  branch = "master"
  name = "github.com/neelance/graphql-go"

[[constraint]]
  version = "v5.0.0"
  name = "github.com/nicksrandall/dataloader"

[[constraint]]
  version = "v0.8.0"
  name = "github.com/pkg/errors"
