required = ["github.com/jteeuwen/go-bindata"]

[[constraint]]
  branch = "master"
  name = "github.com/neelance/graphql-go"

[[constraint]]
  branch = "v2"
  name = "github.com/nicksrandall/dataloader"

[[constraint]]
  branch = "master"
  name = "github.com/pkg/errors"
